---
defaults:
  - _self_
  - override launcher: submitit_slurm

# output directory, generated dynamically on each run
run:
  dir: ${oc.env:SCRATCH}/autoreg/${hydra.job.name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
sweep:
  dir: ${oc.env:SCRATCH}/autoreg/${hydra.job.name}/multiruns/${now:%Y-%m-%d}_${now:%H-%M-%S}
  subdir: ${hydra.job.override_dirname}

job_logging:
  handlers:
    file:
      # Incorporates fix from https://github.com/facebookresearch/hydra/pull/2242
      filename: ${hydra.runtime.output_dir}/${hydra.job.name}.log

launcher:
  submitit_folder: ${hydra.sweep.dir}/.submitit/%j
  timeout_min: 180
  cpus_per_task: 5
  gpus_per_node: 1
  tasks_per_node: 1
  mem_gb: 8
  nodes: 1
  name: ${hydra.job.name}
  stderr_to_stdout: false
  _target_: hydra_plugins.hydra_submitit_launcher.submitit_launcher.SlurmLauncher
  partition:
  qos:
  comment:
  constraint:
  exclude:
  gres:
  cpus_per_gpu:
  gpus_per_task:
  mem_per_gpu:
  mem_per_cpu:
  account: ${oc.env:SLURM_COMPUTE_ACCOUNT}
  signal_delay_s: 120
  max_num_timeout: 0
  additional_parameters: {mail-user: '${oc.env:SLACK_EMAIL_BOT}', mail-type: ALL}
  array_parallelism: 256
  setup: [export HYDRA_FULL_ERROR=1, export NCCL_DEBUG=INFO, 'rsync -tv --info=progress2 /lustre03/project/6003287/hwang1/rs-autoregression-prediction/outputs/sample_for_pretraining/seed-${random_state}/./sample_seed-${random_state}_data-train.h5
        $SLURM_TMPDIR/data_$SLURM_JOB_ID.h5']
