[tool.black]
target-version = ['py38']
exclude = "code/fmri-autoreg"
line_length = 79

[tool.isort]
profile = "black"
src_paths = [
  'code/.*py',
]
line_length = 79
skip_gitignore = true
combine_as_imports = true
