[tool.black]
target-version = ['py311']
exclude = "src/fmri-autoreg"
line_length = 79

[tool.codespell]
skip = '*.ipynb'
ignore-words = ".github/codespell_ignore_words.txt"

[tool.isort]
profile = "black"
src_paths = [
  'code/.*py',
]
line_length = 79
skip_gitignore = true
combine_as_imports = true

[tool.ruff]
exclude = [
    "code/*.ipynb",
    "**/__init__.py",
    "**/tests/*",
    "*build/",
    "code/fmri-autoreg",
    "tools/*/plot_*.py"
]

ignore = [
    "E501",
    "F401",
    "F403",
    "B905",
    "E731",
    "E712"
]
line-length = 79
select = [
    "B",
    "B9",
    "C",
    "E",
    "F",
    "W",
]

[tool.ruff.mccabe]
max-complexity = 18

[tool.ruff.pycodestyle]
max-doc-length = 108

[tool.ruff.pydocstyle]
convention = "google"

[tool.ruff.per-file-ignores]
"*_test.py" = [
    "S101",  # Use of `assert` detected
]
