---
defaults:
  - _self_
  - model: ccn_abstract
  - data: ukbb
  - hydra: scaling

verbose: 2
random_state: 42
return_type: float
convlayer_index: -1
phenotype_file: inputs/connectomes/sourcedata/ukbb/ukbb_pheno.tsv
