---
defaults:
  - _self_
  - hydra: scaling_cpu

predict_variable: sex
predict_variable_type: binary
percentage_sample: 100
# passing extracted feature path is necessary for evaluation
feature_path: ???
