# @package _global_

defaults:
  - override /hydra/launcher: submitit_slurm

# data_dir: /mnt/scratch/data/

hydra:
  launcher:
    timeout_min: 180
    cpus_per_task: 5
    gpus_per_node: 1
    tasks_per_node: 1
    mem_gb: 8
    nodes: 1
    account: ${oc.env:SLURM_COMPUTE_ACCOUNT}
    additional_parameters:
      { mail-user: "${oc.env:SLACK_EMAIL_BOT}", mail-type: ALL }
    array_parallelism: 256
    setup: [export HYDRA_FULL_ERROR=1, export NCCL_DEBUG=INFO]
