defaults:
  - model_checkpoint
  - early_stopping
  - model_summary
  - rich_progress_bar
  - _self_

model_checkpoint:
  dirpath: ${paths.output_dir}/checkpoints
  filename: "epoch={epoch:03d}-val_r2_best={val/r2_best:.3f}"
  monitor: "val/r2_best"
  mode: "max"
  save_last: True
  auto_insert_metric_name: false

early_stopping:
  monitor: "val/r2_best"
  patience: 100
  mode: "max"

model_summary:
  max_depth: -1
