# @package _global_

defaults:
  - _self_
  - data: ukbb
  - model: chebnet_default
  - logger: null
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default
  - optional local: default

task_name: "eval"

tags: ["dev"]

horizon: 6

# this should match the training
seed: null

# passing checkpoint path is necessary for evaluation
ckpt_path: ???
